In [ ]:
%pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 46.8 MB/s eta 0:00:00a 0:00:01

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: pip install --upgrade pip


In [2]:
import numpy as np
print(np.__version__)

2.0.2


In [3]:
b = np.array([[1, 2], [3, 4]])
print("2D Array:\n", b)

2D Array:
 [[1 2]
 [3 4]]


In [4]:
print("Zeros:\n", np.zeros((2, 3)))
print("Ones:\n", np.ones((3, 2)))
print("Full:\n", np.full((2, 2), 7))
print("Empty:\n", np.empty((2, 2)))  # values are uninitialized (random)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Full:
 [[7 7]
 [7 7]]
Empty:
 [[3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323]]


In [6]:
a = np.arange(6)
print("reshape:\n", a.reshape((2, 3)))
print("flatten:\n", a.reshape((2, 3)).flatten())
print("ravel:\n", a.ravel())

reshape:
 [[0 1 2]
 [3 4 5]]
flatten:
 [0 1 2 3 4 5]
ravel:
 [0 1 2 3 4 5]
